#api:
#  url: 'https://api.coindesk.com/v1/bpi/currentprice.json'
#api:
#  url: 'https://api.github.com/users/hadley/orgs'
#api:
#  urls:
#    - 'https://api.coindesk.com/v1/bpi/currentprice.json'
#    - 'https://api.github.com/users/hadley/orgs'
api:
  urls:
    - 'https://api.github.com/orgs/ggobi'
    - 'https://api.github.com/orgs/rstudio'
    - 'https://api.github.com/orgs/rstats'
    - 'https://api.github.com/orgs/ropensci'
