openapi: 3.1.0
info:
  title: GitHub User Organizations API
  description: API to fetch organizations the user belongs to on GitHub
  version: 1.0.0

paths:
  /users/{username}/orgs:
    get:
      summary: List user organizations
      description: Fetch the organizations the user belongs to.
      operationId: listUserOrganizations
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
          description: GitHub username of the user whose organizations is fetched.
      responses:
        '200':
          description: Successful response with an array of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  documentation_url:
                    type: string

components:
  schemas:
    Organization:
      type: object
      properties:
        login:
          type: string
        id:
          type: integer
        node_id:
          type: string
        url:
          type: string
        description:
          type: string
